# Generated by Django 4.2.10 on 2024-12-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_rentcar_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreserve',
            name='car',
        ),
        migrations.RemoveField(
            model_name='carreserve',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='rentcar',
            name='owner',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('mechanic', 'Mechanic')], default='user', max_length=200),
        ),
        migrations.DeleteModel(
            name='CarRenterProfile',
        ),
        migrations.DeleteModel(
            name='CarReserve',
        ),
        migrations.DeleteModel(
            name='RentCar',
        ),
    ]
