# Generated by Django 5.1.4 on 2025-01-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_carreserve_car_remove_carreserve_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqtomechanic',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reqtomechanic',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reqtomechanic',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='reqtomechanic',
            name='longtitude',
            field=models.FloatField(null=True),
        ),
    ]
