# Generated by Django 5.1.4 on 2025-03-02 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_reqtomechanic_address_reqtomechanic_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqtomechanic',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('Payment Pending', 'Payment Pending'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=200),
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('logo', models.FileField(upload_to='fuel_logo')),
                ('fuel_dealer', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReqFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('latitude', models.FloatField(null=True)),
                ('longtitude', models.FloatField(null=True)),
                ('address', models.TextField(null=True)),
                ('link', models.URLField(null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('Payment Pending', 'Payment Pending'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=200)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fuel', to='app.fuel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_location', to='app.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_fuel', to='app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_user', to='app.userprofile')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_s', to='app.fuel')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_fuel', to='app.reqfuel')),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acholdername', models.CharField(max_length=100)),
                ('accno', models.PositiveBigIntegerField()),
                ('cvv', models.IntegerField()),
                ('exp', models.CharField(max_length=100)),
                ('amount', models.PositiveBigIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_pay_fuel', to='app.userprofile')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_pay', to='app.fuel')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pay_fuel', to='app.reqfuel')),
            ],
        ),
    ]
