# Generated by Django 5.1.4 on 2025-03-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_reqtomechanic_status_fuel_reqfuel_feedbackfuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('mechanic', 'Mechanic'), ('fuels', 'Fuels')], default='user', max_length=200),
        ),
    ]
