# Generated by Django 5.1.4 on 2025-03-03 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_fuelrequest_alter_feedbackfuel_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('latitude', models.FloatField(null=True)),
                ('longtitude', models.FloatField(null=True)),
                ('address', models.TextField(null=True)),
                ('link', models.URLField(null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('Payment Pending', 'Payment Pending'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=200)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fuel', to='app.fuel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_location', to='app.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_fuel', to='app.userprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='feedbackfuel',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_fuel', to='app.reqfuel'),
        ),
        migrations.AlterField(
            model_name='userpaymentfuel',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pay_fuel', to='app.reqfuel'),
        ),
        migrations.DeleteModel(
            name='FuelRequest',
        ),
    ]
