# Generated by Django 5.1.4 on 2025-03-03 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_reqfuel_alter_feedbackfuel_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reqfuel',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='fuel',
            name='location',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.location'),
        ),
        migrations.AlterField(
            model_name='reqfuel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_fuel', to=settings.AUTH_USER_MODEL),
        ),
    ]
