# Generated by Django 5.1.4 on 2025-03-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_longtitude_reqfuel_longitude_fuel_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='quantity',
        ),
        migrations.AddField(
            model_name='reqfuel',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
