# Generated by Django 5.1.4 on 2025-03-03 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_fuel_quantity_reqfuel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reqfuel',
            name='location',
        ),
        migrations.AlterField(
            model_name='reqfuel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_fuel', to='app.userprofile'),
        ),
    ]
