# Generated by Django 5.1.4 on 2025-03-03 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_reqfuel_location_alter_reqfuel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqfuel',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('Payment Pending', 'Payment Pending'), ('pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Out For Delivery', 'Out For Delivery')], default='pending', max_length=200),
        ),
        migrations.CreateModel(
            name='BillFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fuel')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reqfuel')),
            ],
        ),
    ]
