# Generated by Django 5.1.4 on 2025-03-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_reqfuel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqfuel',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('Payment Pending', 'Payment Pending'), ('pending', 'Pending'), ('OrderConfirmed', 'OrderConfirmed'), ('Out For Delivery', 'Out For Delivery'), ('Cancelled', 'Cancelled')], default='pending', max_length=200),
        ),
    ]
