# Generated by Django 5.1.6 on 2025-03-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_reqfuel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='platform_fee',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='billfuel',
            name='platform_fee',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
