# Generated by Django 5.1.6 on 2025-03-12 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_category_cart_order_product_orderitem_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_number', models.PositiveBigIntegerField()),
                ('cvv', models.IntegerField()),
                ('expiry_date', models.CharField(max_length=7)),
                ('amount', models.PositiveBigIntegerField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='app.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
